### ISSUE TITLE
Failed to open native connection to Cassandra

### ISSUE THREAD

**Issue by tyuengithub** [MicrosoftLearning/DP-060T00A-Migrating-your-Database-to-Cosmos-DB#2]
Hi, new to spark and Azure DataBrick.
  
I'm getting failed to connect to my Cassandra cluster . . . We have setup a private net from AWS to Azure.

**Error Message:** java.io.IOException: Failed to open native connection to Cassandra at [ip-address]: 9042
at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:168)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$8.apply(CassandraConnector.scala:154)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:32)
	at com.datastax.spark.connector.cql.RefCountedCache.syncAcquire(RefCountedCache.scala:69)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:57)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:79)
	at com.datastax.spark.connector.cql.CassandraConnector.withSessionDo(CassandraConnector.scala:111)
	at com.datastax.spark.connector.rdd.partitioner.dht.TokenFactory$.forSystemLocalPartitioner(TokenFactory.scala:98)
	at org.apache.spark.sql.cassandra.CassandraSourceRelation$.apply(CassandraSourceRelation.scala:272)
	at org.apache.spark.sql.cassandra.DefaultSource.createRelation(DefaultSource.scala:56)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:347)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:311)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:297)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:203)

**Comment by tyuengithub** [comment]
my mistake, i did not import com.microsoft.azure.cosmosdb:azure-cosmos-cassandra-spark-helper:1.0.0

**Comment by GraemeMalcolm** [comment]
Non-repo in course labs
